---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sample-app-ingress
  namespace: observability
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - ramosecajado1.com
    - ramosecajado2.com
    secretName: ingress-cert
  rules:
  - host: ramosecajado1.com
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: kuard
            port:
              number: 80
  - host: ramosecajado2.com
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: kuard
            port:
              number: 80